apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-cluster
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/thiagobotelho/argocd-gitops.git
    targetRevision: main
    path: overlays/cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true