apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-apps
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "18"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/thiagobotelho/prometheus-gitops.git
    targetRevision: main
    path: overlays/desenvolvimento
  destination:
    server: https://kubernetes.default.svc
    namespace: observability-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - PruneLast=true
