apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  source:
    repoURL: https://github.com/thiagobotelho/grafana-gitops.git
    targetRevision: main
    path: overlays/desenvolvimento
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true, SkipDryRunOnMissingResource=true, PruneLast=true]
